os:
- linux
- osx
- windows
language: rust
cache: cargo
script:
- cargo build --verbose --all
- cargo test --verbose test::test_ffi
- cargo test --verbose test::test_natpmp
- cargo doc
deploy:
  provider: cargo
  token:
    secure: IL0kMoVom8dCuxoHZ+ZHBRxlUI4fCLXi5GF5K3SZ2YGB0zaLr+mo+8Tc9IWVab5aMPnb7hxCZn/WFpYbH4qpJoUxruZEVce4xp1aoW/DgDPkKgwzU2UX4+TzSQwZakfwQcZNVolzOMGOVfuEPMOdzwORr5nCW1jQpt7O6c1W25Uj+PBynFh5Ehngc8ypOlPn08hEEqXP/PNlq5wvUCKk4G11NhuCuedIFP2lb0NXcPKGi7qSwSy1TkwkQqZlA5qZm2ZGJiagtWy4CcDVx8ljD0pUAkVhWV31i6Koc/ieV+ueFn9P3O6bjhKP4qJZ4DFEU9CMqRgH251mQIlhdN2zCgPeWX0tek0OOWw5pKpzXXibpAo4iB72EY2jGz9aU71yWd40CBcf8oMU63RJ0b8ArXp9z5Rkgz7XoRB93quQqNyzi4Bk9sPRJWFLqQ/K8cFikSKiDNfvs4l/fedhztLlRIeRX1Eh7T1qPvXSCP05qujwfWgnRs+Fp5G5S9fjh3M0HehLPW71SZ8LHm4Is+8FhR1WATxoShltftZ/IE/78Oo4h9rT4BS7htdvZgH3k2uhZWEX/0MD2C1N2qqk7AsirnZ4p6stDgMpNYxJ2ui48EEfH80AtCusDYTms12nOrnY3xyGwpCJWqhJ4z1/gFYhFzoIwFygthS0/jT6t1OhoJk=
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
