language: rust
rust:
  - stable
script:
  - cargo build --verbose --all
  - cargo test --verbose test::test_ffi
  - cargo test --verbose test::test_natpmp
  - cargo doc --verbose
deploy:
  provider: cargo
  token:
    secure: hvLs/JAuPbxsUrk/j4x3zSxycj3m6oMyT/uIAi7+DvFPDxse+mr7M9pjeRX2iADG/XQng80MXJ9kGIJ4mtVh469o00AXebG2dgprCDD5HrMzEJxjsabIC90vR5W3ntp3H5Dx3QFYZx8WDE2NFBf9lpV3vxAFV/AtyHWR8U50HbLrMJ9WHP76uRLJu6tWOEDRWGtBXZEEUiR6y/1uoVOka1V6SrKqNxaAhErMKsLKOjWYQINWgq0RTX4jregCpj5PyLIc+vw7WUFwnIqwB3bejlKxtw2ycvaELbVwgHItBIOWpVljmRE2utCbY8H6UBeUJTBRTq68Fjj8QtwWwTwLAeShVLOojyeVX9kOv8RjHFn1dotde8h9opyKoMlCfJRUExCbtbfcQh0B9fNn7cyAkAujlQFGXlBSIn8vuHSPIeo6sffUbTyJoJsb7B4Z9g4FgAdlcAZSRpGHcnbxqhCtFmcWIGEkhk8ggRWUbYpWlhQueFY85lX0i2aL2n4riwcPWT8PHlV4J0xcBiVIFIPZQUKo7/5FpzZsVngFd0/IrH7jqxMjVb2QUTNviZzqyQ4WV9guPYMGatURwWP6TZuUjVeZRMETwqL7HWQ1TMNx8+/ONlWYpSaZBQZLnm5tOyiR9/XG/ynDx0ntCKa9XLFFqqdHU+lkUsZsZjfNaQi1mOA=
