language: rust
script:
  - cargo build --verbose --all
  - cargo test --verbose test::test_ffi
  - cargo test --verbose test::test_natpmp
  - cargo doc --verbose
deploy:
  provider: cargo
  token:
    secure: "OXAzW4nCfnGgensR24gp6N6QTiTjZu4z7nlzhh9zk44iMSZZRk8AC47s4vxlR9x6zIbPRxjTrdg080krARJA+uDnVIu6gde2aczVJiq+oq0nFZz415LSTRNTR45d/SI09ylVrUdZHJrmzGBm0cQWwN+5k3lNg9octV2fQOb7Grl7w+Gm7eMQ2wFVpTpHcvFQQQx02Cm+fbCMO/iTl0xYk1YZ3M4OlFTeb78p9y6tcJTgG6SNEYMmFQtdRPbyagMzqcOH7zAAvoHxMf7CHpSaotj/j8CDMwlZnbSR2KtpObW0ula87MT9jT/jtJ2T3JzZAKwJoTkzAkbZG4iGadQ4lIqnQAR3aNu6mTLaYQQ9T+LR0+zUF3q8sAxD0R1de4vIemVjw1GatxwiJKGvmuKtoxci2gJiAS+E7VmSxrH+kIMNmVuwArrLVUbpFhK/XsOJ1UrO8TLb1pobdUTT3asSVVjWgVF9jB8Pwt4PcL58Wc3wmjpVuYPa8NiT6+FX4wx+MI2HoczTOa4FdeteDtZdQtYk2tx2AFSQGM2yfX3LIAJwK70opTVelLBM1g/PceolxOxXOefHqko/xS3zA6hL4cnG1F1LObtBTsa3s4tBtUxs+Yay2PXzQJoLhtX14bO8M4nR1+AVnxKuNM3jYq5+LIQ92N1ldotjFpuetaf1L/I="
