os:
- linux
- osx
- windows
language: rust
cache: cargo
script:
- cargo build --verbose --all
- cargo test --verbose test::test_ffi
- cargo test --verbose test::test_natpmp
- cargo doc
deploy:
  provider: cargo
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
  token:
    secure: Qoc2/oWQWpt6syR88b1HjdbgxshEq8EhcUKMaUSDXcGIS3EyYQytntMBd9zza/5NggNsfxeIajlPlnCC21c8ZoHmRBxHCGJKtPSiHNHGd0vroClZ33ZpiJ0pubMZ8kOMh24tIb5XbYskBAp5VvoA/NiheGvK/RJFUcrBDjKkLKURfK3RvL3Pen9C9/VepZRzCyF/NX58pV2RbjCxUfc54jXw3Ao+T6HO7ITtDhwdK/LcUmzmM+8h5Qo5ZE1/VCsSFCfNIoyX07oI8TTwaP1yS+duImr36r3KceARo0DzSQAKRH6eJpLmxgb+m78R+54oSnCLRHp2TgxV6pR0uO8s9MygEQmwQQEPlDdEV5VbJdHbEgjgNFQneiLDL7YNYxZCgvNyvqS83IBKakI4x0p9XvmonbzO6z+SC8FZ+GDgECFfrxgAK9iVfhCKDOoNFtYAZ78Am1j3R2TxA63mAYQ/O9xXlDPpD2G1cJE10QG0nBdRcc+JSx3uARuE924pKYjNvsFvTJ4VEqvC80h01WjwYMDU5TlpIMELAnoFDEjVXanEB2Pb3HZTQpBAE6p3Rug3hDcbATebasmBiFxgbM4SFiWyBwwGo3DbQu/siXGx8flHo3MAJuE9pse3CsXnkEAozQmxxsZ2K0+dYYXgwsfVkqEtlKUKXmmXg4JInPSVTfU=
