os:
- linux
- osx
- windows
language: rust
script:
- cargo build --verbose --all
- cargo test --verbose test::test_ffi
- cargo test --verbose test::test_natpmp
- cargo doc
deploy:
  provider: cargo
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
  token:
    secure: TSqENzavk/jJ6MW9g/RI2uOcWAIOdZwXikOOBFwQVpBuZBUE5jWmghZsw2uA66lasr0O2On5wId3YFZtQuAUSx76jQyPyayLc4yBFvWF2/zrRVsth4nnEmfkkTbLVIu7j6UGxyu5M7TCMUxRt8uwHEpvNtrdQeRm1TITwyDW22iSjOQZtynGrYUM9fe52KIPJhskHnyBBB/LeF9Fp3jk6DtqZLIsYhyDl1Nem7OtWnS0K/uxIFEJpPIvsdwr85i321y3fCQd6CcO6DaMcKaRXU4IvIq2RIhUu/oo6RHU6OiWli83mU5RJpnjwb74dkScIfagd3riumES0oGIAAOm+prndgHMVWjmaN09ABN34gFd0cT41OpXX5h5GvuZMc1HoexWdjTS2F1oGE0nPteILiHvq+UYS39PQSxIKNvFe9ng38+oBoc8uNF6bVxUaAYGPbxUkBZ+ZqkPbQ6tVfGrHM56zknVxKQKGlW0V6GF82OMG3BA70y1mSVjZr1UJ6/gDnNXb80kpRwg+yra5sMQ3DgV0q34aad5pUuFH+szT+ix92bRyCsrbNxSG/vSeBJCWoDIZzTDmoIAiBaLuofmCHMa3m/Qc/wl0RXiN8GTJQqHWYiaSWdyVeiiEHpU0WVYRdrinVDIkCgBr5pkgO4U8zunFMulslJ3V9sTNt3mw/A=
