[package]
name = "libnatpmp"
version = "0.1.2"
authors = ["fengyingcai <fengyc.work@gmail.com>"]
build = "build.rs"
description = "A NAT-PMP (IETF RFC 6886) library in rust."
license = "MIT"
keywords = ["natpmp", "rfc6886", "nat", "portmapping"]
repository = "https://github.com/fengyc/libnatpmp"
homepage = "https://github.com/fengyc/libnatpmp"
documentation = "https://docs.rs/libnatpmp/"

[build-dependencies]
cc = "1.0"      # compile native c