[package]
name = "natpmp"
version = "0.1.15"
authors = ["fengyingcai <fengyc.work@gmail.com>"]
description = "NAT-PMP client library"
homepage = "https://github.com/fengyc/natpmp"
repository = "https://github.com/fengyc/natpmp"
documentation = "https://docs.rs/natpmp/"
readme = "README.md"
keywords = ["natpmp", "rfc6886", "nat", "portmapping"]
categories = ["network-programming"]
license = "MIT"
build = "build.rs"

[badges]
travis-ci = { repository = "fengyc/natpmp" }

[build-dependencies]
cc = "1.0"      # compile native c