[package]
name = "natpmp"
version = "0.1.11"
authors = ["fengyingcai <fengyc.work@gmail.com>"]
build = "build.rs"
description = "A NAT-PMP (IETF RFC 6886) library in rust."
license = "MIT"
keywords = ["natpmp", "rfc6886", "nat", "portmapping"]
repository = "https://github.com/fengyc/natpmp"
homepage = "https://github.com/fengyc/natpmp"
documentation = "https://docs.rs/natpmp/"
readme = "README.md"

[build-dependencies]
cc = "1.0"      # compile native c