name: "Publish Release"

on:
  release:
    tags:
      - "v*"
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Rust toolchain
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Cargo publish
      - name: Cargo publish
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: |
          cargo publish --token "$CARGO_TOKEN"